### ISSUE TITLE
create train.rec and test.rec from your tinyimageset

### ISSUE THREAD

**Issue by kaishijeng** [shuokay/resnet#1]
shuokay

I have a titanx board and like to try your resnet if you can show me how to generate train.rec and test.rec from your tiny-imageset.zip

Thanks,

**Comment by shuokay** [comment]
MxNet have provided a tool to generate images to iterdata, when you have build the mxnet project, it is located in mxnet/bin/im2rec

**Comment by kaishijeng** [comment]
I am aware of im2rec tool. But it requires input image list file which consists of the following format:
Image List Format: unique-image-index label[s] path-to-image

I don't see this list in your tiny-imageset.zip

**Comment by shuokay** [comment]
You should generate the input image list file by yourself.Please refer to [cs231n project](http://cs231n.stanford.edu/project.html) for more information about tiny imagenet dataset

**Comment by pengpaiSH** [comment]
@shuokay I have downloaded the tinyImageNet dataset and use """im2rec""" tool to generate the `train.rec` and `val.rec`. However, it seems that the training procedure is extremely slow! Is there anything wrong? I use Texla K20 GPU. By the way, how much accuracy do you get after 10 epochs iteration?
![image](https://cloud.githubusercontent.com/assets/3724085/12137520/43113666-b48c-11e5-9be5-6502844daae9.png)

**Comment by shuokay** [comment]
Please refer to #3
